[theme]
primaryColor = "#FF5532"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F8F8"
textColor = "#221E1E"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
